server {
    listen 80;
    listen [::]:80;
    server_name vpnhide.duckdns.org;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name vpnhide.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/vpnhide.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vpnhide.duckdns.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /usr/share/nginx/html;
    index PrivacyPolicy.html UserAgreement.html;

    location ~ \.html$ {
        return 404;
    }

    location / {
        try_files $uri $uri/ $uri.html =404;
    }
}